In [1]:
import numpy as np
import pandas as pd

In [2]:
weather_hist = pd.read_csv('weatherHistory.csv')

In [3]:
weather_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96450 entries, 0 to 96449
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            96450 non-null  object 
 1   Summary                   96450 non-null  object 
 2   Precip Type               95930 non-null  object 
 3   Temperature (C)           96450 non-null  float64
 4   Apparent Temperature (C)  96450 non-null  float64
 5   Humidity                  96450 non-null  float64
 6   Wind Speed (km/h)         96445 non-null  float64
 7   Wind Bearing (degrees)    96450 non-null  int64  
 8   Visibility (km)           96442 non-null  float64
 9   Loud Cover                96450 non-null  int64  
 10  Pressure (millibars)      96443 non-null  float64
 11  Daily Summary             96450 non-null  object 
dtypes: float64(6), int64(2), object(4)
memory usage: 8.8+ MB


In [4]:
weather_hist.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [5]:
weather_hist.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96450.000000              96450.000000  96450.000000   
mean         11.932456                 10.854838      0.734912   
std           9.551517                 10.696820      0.195462   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96445.000000            96450.000000     96442.000000     96450.0   
mean           10.809563              187.507838        10.347331         0.0   
std             6.910700              107.384208         4.192359         0.0   
min             0.000000                0.000000         0.000000         0.0   
25%             5.828200              116.000000         8.339800         0.0   
50%             9.965900              180.000000        10.046400         0.0   
75%            14.135800              290.000000        14.812000         0.0   
max            55.931400              359.000000        16.100000         0.0   

       Pressure (millibars)  
count          96443.000000  
mean            1003.235465  
std              116.975940  
min                0.000000  
25%             1011.900000  
50%             1016.450000  
75%             1021.090000  
max             1046.380000

In [6]:
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 96450


In [7]:
print ("Unique values are:\n",weather_hist.nunique())

Unique values are:
 Formatted Date              96426
Summary                        24
Precip Type                     4
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2483
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
Daily Summary                 214
dtype: int64


In [8]:

duplicates = weather_hist[weather_hist.duplicated()]

# Print the number of duplicate rows, if any
num_duplicates = len(duplicates)
if num_duplicates > 0:
    print("\n")
    print(f"{num_duplicates} duplicate rows found in Weathe History Dataset.")
    print("\n")
    print(duplicates)
else:
    print("No duplicate rows found in WeatherHistory.")



24 duplicate rows found in Weathe History Dataset.


                      Formatted Date        Summary Precip Type  \
36071  2010-08-02 00:00:00.000 +0200          Clear        rain   
36072  2010-08-02 01:00:00.000 +0200          Clear        rain   
36073  2010-08-02 02:00:00.000 +0200          Clear        rain   
36074  2010-08-02 03:00:00.000 +0200          Clear        rain   
36075  2010-08-02 04:00:00.000 +0200          Clear        rain   
36076  2010-08-02 05:00:00.000 +0200          Clear        rain   
36077  2010-08-02 06:00:00.000 +0200          Clear        rain   
36078  2010-08-02 07:00:00.000 +0200          Clear        rain   
36079  2010-08-02 08:00:00.000 +0200          Clear        rain   
36080  2010-08-02 09:00:00.000 +0200          Clear        rain   
36081  2010-08-02 10:00:00.000 +0200          Clear        rain   
36082  2010-08-02 11:00:00.000 +0200          Clear        rain   
36083  2010-08-02 12:00:00.000 +0200          Clear        rain   
36084  

In [9]:
# Removing duplicated values
weather_hist.drop_duplicates(inplace=True)
# Again checking for duplicated values
print("Duplicated Values: ", weather_hist.duplicated().sum())

Duplicated Values:  0


In [10]:
#Printing the shape of dataset after deleting Duplicates
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 96426


In [11]:
# Checking missing values

# Check for null values in the DataFrame
null_values = weather_hist.isnull().sum()

# Print the count of null values in each column
print('Checking the NULL Values in  WeatherHistory Dataset..\n')

# Check if there are any null values
if null_values.sum() == 0:
    print(f'\n There are no null values in the given dataset.')
else:
    columns_with_null_values = null_values[null_values > 0].index.tolist()
    # Loop over the columns with null values and print the count of null values for each column
    for column in columns_with_null_values:
        count = null_values[column]
        print(f"Column '{column}' has {count} null values.")

Checking the NULL Values in  WeatherHistory Dataset..

Column 'Precip Type' has 520 null values.
Column 'Wind Speed (km/h)' has 5 null values.
Column 'Visibility (km)' has 8 null values.
Column 'Pressure (millibars)' has 7 null values.


In [12]:
# Handling missing values
weather_hist['Precip Type'].value_counts()

rain    85191
snow    10712
?           2
%           1
Name: Precip Type, dtype: int64

In [13]:
# Remove rows with missing values in 'Precip Type' column
weather_hist = weather_hist[(weather_hist['Precip Type'] != '?') & (weather_hist['Precip Type'] != '%')]

# Verify the changes
weather_hist['Precip Type'].value_counts()


rain    85191
snow    10712
Name: Precip Type, dtype: int64

In [14]:
# Remove rows with null values in specified columns
weather_hist = weather_hist.dropna(subset=['Precip Type', 'Wind Speed (km/h)', 'Visibility (km)', 'Pressure (millibars)'])



In [15]:
# Re-check Handling Missing Values
missing_values = weather_hist.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64


In [16]:
#Printing the shape of dataset after deleting Duplicates
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 95883


In [17]:
# Remove the 'Daily Summary' column from the DataFrame
weather_hist = weather_hist.drop('Daily Summary', axis=1)



Here are some reasons to justify deleting the 'Daily Summary' column from the entire dataset:

Irrelevance for Analysis: The 'Daily Summary' column contains textual descriptions of daily weather summaries. If your analysis focuses more on numerical weather data (such as temperature, humidity, etc.) rather than descriptive summaries, keeping this column may not add value to your analysis.

Reduced Memory Usage: Textual data can occupy more memory compared to numerical data. By removing the 'Daily Summary' column, you can reduce the overall memory usage of your dataset, which can be beneficial for large datasets or when working with memory-constrained environments.

Simplicity and Focus: Removing irrelevant columns can simplify your dataset and focus your analysis on the key variables of interest. This can make your analysis more manageable and easier to interpret.

Enhanced Performance: With fewer columns, operations on the dataset, such as calculations or transformations, may be faster and more efficient, leading to improved performance in data processing tasks.

Consistency and Standardization: By removing a column that contains descriptive text, you can ensure that your dataset remains consistent in terms of data types (e.g., numeric data) and standardizes the format for easier processing and analysis.

In [18]:
# Define a dictionary mapping current weather summaries to new categories
weather_mapping = {
   'Clear': 'Clear Skies',
    'Partly Cloudy': 'Cloudy Skies',
    'Mostly Cloudy': 'Cloudy Skies',
    'Overcast': 'Cloudy Skies',
    'Foggy': 'Foggy Day',
    'Breezy and Foggy': 'Foggy Day',
    'Windy and Foggy': 'Foggy Day',
    'Breezy': 'Breezy Day',
    'Breezy and Mostly Cloudy': 'Breezy Day',
    'Breezy and Partly Cloudy': 'Breezy Day',
    'Breezy and Overcast': 'Breezy Day',
    'Windy': 'Windy Day',
    'Windy and Mostly Cloudy': 'Windy Day',
    'Windy and Partly Cloudy': 'Windy Day',
    'Windy and Overcast': 'Windy Day',
    'Humid and Mostly Cloudy': 'Humid Day',
    'Humid and Partly Cloudy': 'Humid Day',
    'Humid and Overcast': 'Humid Day',
    'Dry': 'Dry Day',
    'Dry and Mostly Cloudy': 'Dry Day',
    'Dry and Partly Cloudy': 'Dry Day',
    'Light Rain': 'Rainy Day',
    'Drizzle': 'Rainy Day',
    'Rain': 'Rainy Day'
}

# Create a new column 'Weather Category' based on the mapping
weather_hist['Summary'] = weather_hist['Summary'].map(weather_mapping)

# Display the value counts of the new column
print(weather_hist['Summary'].value_counts())


Cloudy Skies    76035
Clear Skies     10744
Foggy Day        7155
Breezy Day       1484
Windy Day         155
Dry Day           134
Rainy Day         112
Humid Day          64
Name: Summary, dtype: int64


In [19]:
# Verify the changes
weather_hist.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 95883 entries, 0 to 96449
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            95883 non-null  object 
 1   Summary                   95883 non-null  object 
 2   Precip Type               95883 non-null  object 
 3   Temperature (C)           95883 non-null  float64
 4   Apparent Temperature (C)  95883 non-null  float64
 5   Humidity                  95883 non-null  float64
 6   Wind Speed (km/h)         95883 non-null  float64
 7   Wind Bearing (degrees)    95883 non-null  int64  
 8   Visibility (km)           95883 non-null  float64
 9   Loud Cover                95883 non-null  int64  
 10  Pressure (millibars)      95883 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 8.8+ MB


In [20]:
from datetime import datetime

# Define the format string for the date
format_string = "%Y-%m-%d %H:%M:%S.%f %z"

# Function to check if a value is in the correct format
def check_date_format(value):
    try:
        datetime.strptime(value, format_string)
        return True
    except ValueError:
        return False

# Apply the function to each value in the 'Formatted Date' column and create a new column 'is_valid_date'
weather_hist['is_valid_date'] = weather_hist['Formatted Date'].apply(check_date_format)

# Filter the DataFrame to show only rows where 'is_valid_date' is False
invalid_dates = weather_hist[~weather_hist['is_valid_date']]

# Display the rows with invalid dates
print("Rows with invalid dates:")
print(invalid_dates[['Formatted Date', 'is_valid_date']])


Rows with invalid dates:
Empty DataFrame
Columns: [Formatted Date, is_valid_date]
Index: []


In [21]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Label encode object columns
object_columns = ['Summary', 'Precip Type']
for col in object_columns:
    weather_hist[col+'_encoded'] = label_encoder.fit_transform(weather_hist[col])

# Convert 'Formatted Date' to datetime format with utc=True
weather_hist['Formatted Date'] = pd.to_datetime(weather_hist['Formatted Date'], utc=True)

# Extract year, month, day, and hour
weather_hist['Year'] = weather_hist['Formatted Date'].dt.year
weather_hist['Month'] = weather_hist['Formatted Date'].dt.month
weather_hist['Day'] = weather_hist['Formatted Date'].dt.day
weather_hist['Hour'] = weather_hist['Formatted Date'].dt.hour

# Create dictionaries for mapping encoded values to original labels
summary_mapping = dict(zip(weather_hist['Summary_encoded'], weather_hist['Summary']))
precip_mapping = dict(zip(weather_hist['Precip Type_encoded'], weather_hist['Precip Type']))

# Display the updated DataFrame and the mapping dictionaries
print("Weather History DataFrame:")
weather_hist[['Summary', 'Precip Type', 'Summary_encoded', 'Precip Type_encoded', 'Year', 'Month', 'Day', 'Hour']].head()



C:\Users\student\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Weather History DataFrame:


Summary Precip Type  Summary_encoded  Precip Type_encoded  Year  \
0  Cloudy Skies        rain                2                    0  2006   
1  Cloudy Skies        rain                2                    0  2006   
2  Cloudy Skies        rain                2                    0  2006   
3  Cloudy Skies        rain                2                    0  2006   
4  Cloudy Skies        rain                2                    0  2006   

   Month  Day  Hour  
0      3   31    22  
1      3   31    23  
2      4    1     0  
3      4    1     1  
4      4    1     2

In [22]:
weather_hist

Formatted Date       Summary Precip Type  Temperature (C)  \
0     2006-03-31 22:00:00+00:00  Cloudy Skies        rain         9.472222   
1     2006-03-31 23:00:00+00:00  Cloudy Skies        rain         9.355556   
2     2006-04-01 00:00:00+00:00  Cloudy Skies        rain         9.377778   
3     2006-04-01 01:00:00+00:00  Cloudy Skies        rain         8.288889   
4     2006-04-01 02:00:00+00:00  Cloudy Skies        rain         8.755556   
...                         ...           ...         ...              ...   
96445 2016-09-09 17:00:00+00:00  Cloudy Skies        rain        26.016667   
96446 2016-09-09 18:00:00+00:00  Cloudy Skies        rain        24.583333   
96447 2016-09-09 19:00:00+00:00  Cloudy Skies        rain        22.038889   
96448 2016-09-09 20:00:00+00:00  Cloudy Skies        rain        21.522222   
96449 2016-09-09 21:00:00+00:00  Cloudy Skies        rain        20.438889   

       Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                      7.388889      0.89            14.1197   
1                      7.227778      0.86            14.2646   
2                      9.377778      0.89             3.9284   
3                      5.944444      0.83            14.1036   
4                      6.977778      0.83            11.0446   
...                         ...       ...                ...   
96445                 26.016667      0.43            10.9963   
96446                 24.583333      0.48            10.0947   
96447                 22.038889      0.56             8.9838   
96448                 21.522222      0.60            10.5294   
96449                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                         251          15.8263           0   
1                         259          15.8263           0   
2                         204          14.9569           0   
3                         269          15.8263           0   
4                         259          15.8263           0   
...                       ...              ...         ...   
96445                      31          16.1000           0   
96446                      20          15.5526           0   
96447                      30          16.1000           0   
96448                      20          16.1000           0   
96449                      39          15.5204           0   

       Pressure (millibars)  is_valid_date  Summary_encoded  \
0                   1015.13           True                2   
1                   1015.63           True                2   
2                   1015.94           True                2   
3                   1016.41           True                2   
4                   1016.51           True                2   
...                     ...            ...              ...   
96445               1014.36           True                2   
96446               1015.16           True                2   
96447               1015.66           True                2   
96448               1015.95           True                2   
96449               1016.16           True                2   

       Precip Type_encoded  Year  Month  Day  Hour  
0                        0  2006      3   31    22  
1                        0  2006      3   31    23  
2                        0  2006      4    1     0  
3                        0  2006      4    1     1  
4                        0  2006      4    1     2  
...                    ...   ...    ...  ...   ...  
96445                    0  2016      9    9    17  
96446                    0  2016      9    9    18  
96447                    0  2016      9    9    19  
96448                    0  2016      9    9    20  
96449                    0  2016      9    9    21  

[95883 rows x 18 columns]

In [23]:
print("\nSummary Mapping:")

summary_mapping


Summary Mapping:


{2: 'Cloudy Skies',
 4: 'Foggy Day',
 0: 'Breezy Day',
 1: 'Clear Skies',
 5: 'Humid Day',
 7: 'Windy Day',
 3: 'Dry Day',
 6: 'Rainy Day'}

In [24]:
weather_hist['Summary'].value_counts()

Cloudy Skies    76035
Clear Skies     10744
Foggy Day        7155
Breezy Day       1484
Windy Day         155
Dry Day           134
Rainy Day         112
Humid Day          64
Name: Summary, dtype: int64

In [25]:
print("\nPrecip Type Mapping:")


precip_mapping


Precip Type Mapping:


{0: 'rain', 1: 'snow'}

In [26]:
# Assuming 'weather_hist' is your DataFrame

# Use factorize to encode 'Summary' and 'Precip Type' columns
weather_hist['Summary_encoded'], summary_mapping_index = weather_hist['Summary'].factorize()
weather_hist['Precip Type_encoded'], precip_mapping_index = weather_hist['Precip Type'].factorize()

# Display the mapping indexes
print("Summary Mapping Index:")
print(summary_mapping_index)

print("\nPrecip Type Mapping Index:")
print(precip_mapping_index)


Summary Mapping Index:
Index(['Cloudy Skies', 'Foggy Day', 'Breezy Day', 'Clear Skies', 'Humid Day',
       'Windy Day', 'Dry Day', 'Rainy Day'],
      dtype='object')

Precip Type Mapping Index:
Index(['rain', 'snow'], dtype='object')


In [27]:
# Assuming df is your DataFrame

# Get the unique values in the 'Summary' column before encoding
summary_unique_values = weather_hist['Summary'].unique()

# Get the unique values in the 'Precip Type' column before encoding
precip_unique_values = weather_hist['Precip Type'].unique()

# Display the unique values
print("Unique values in 'Summary' column before encoding:")
print(summary_unique_values)

print("\nUnique values in 'Precip Type' column before encoding:")
print(precip_unique_values)


Unique values in 'Summary' column before encoding:
['Cloudy Skies' 'Foggy Day' 'Breezy Day' 'Clear Skies' 'Humid Day'
 'Windy Day' 'Dry Day' 'Rainy Day']

Unique values in 'Precip Type' column before encoding:
['rain' 'snow']


In [28]:
# Drop original categorical columns
weather_hist = weather_hist.drop(columns=['Summary', 'Precip Type', 'Formatted Date'])

# Display the updated DataFrame
print("Encoded Weather History DataFrame:")
weather_hist.head()


Encoded Weather History DataFrame:


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   is_valid_date  Summary_encoded  Precip Type_encoded  Year  Month  Day  Hour  
0           True                0                    0  2006      3   31    22  
1           True                0                    0  2006      3   31    23  
2           True                0                    0  2006      4    1     0  
3           True                0                    0  2006      4    1     1  
4           True                0                    0  2006      4    1     2

In [29]:
weather_hist['is_valid_date'].value_counts().get(False, 0)


0

In [30]:
weather_hist.shape

(95883, 15)

In [31]:
# Assuming df is your DataFrame
columns_to_remove = ['is_valid_date']
weather_hist = weather_hist.drop(columns=columns_to_remove)

# Display the updated DataFrame
weather_hist.head()


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   Summary_encoded  Precip Type_encoded  Year  Month  Day  Hour  
0                0                    0  2006      3   31    22  
1                0                    0  2006      3   31    23  
2                0                    0  2006      4    1     0  
3                0                    0  2006      4    1     1  
4                0                    0  2006      4    1     2

In [32]:
# Rename the columns
weather_hist = weather_hist.rename(columns={'Summary_encoded': 'Summary', 'Precip Type_encoded': 'Precip Type'})

# Display the updated DataFrame
print("Updated Weather History DataFrame:")
weather_hist.head()


Updated Weather History DataFrame:


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   Summary  Precip Type  Year  Month  Day  Hour  
0        0            0  2006      3   31    22  
1        0            0  2006      3   31    23  
2        0            0  2006      4    1     0  
3        0            0  2006      4    1     1  
4        0            0  2006      4    1     2

In [33]:
weather_hist.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95883 entries, 0 to 96449
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Temperature (C)           95883 non-null  float64
 1   Apparent Temperature (C)  95883 non-null  float64
 2   Humidity                  95883 non-null  float64
 3   Wind Speed (km/h)         95883 non-null  float64
 4   Wind Bearing (degrees)    95883 non-null  int64  
 5   Visibility (km)           95883 non-null  float64
 6   Loud Cover                95883 non-null  int64  
 7   Pressure (millibars)      95883 non-null  float64
 8   Summary                   95883 non-null  int64  
 9   Precip Type               95883 non-null  int64  
 10  Year                      95883 non-null  int64  
 11  Month                     95883 non-null  int64  
 12  Day                       95883 non-null  int64  
 13  Hour                      95883 non-null  int64  
dtypes: flo

In [34]:
missing_values = weather_hist.isnull().sum()
print("Missing values:")
missing_values


Missing values:


Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Summary                     0
Precip Type                 0
Year                        0
Month                       0
Day                         0
Hour                        0
dtype: int64

In [35]:
duplicate_rows = weather_hist[weather_hist.duplicated()]
print("\nDuplicate rows:")
duplicate_rows



Duplicate rows:


Empty DataFrame
Columns: [Temperature (C), Apparent Temperature (C), Humidity, Wind Speed (km/h), Wind Bearing (degrees), Visibility (km), Loud Cover, Pressure (millibars), Summary, Precip Type, Year, Month, Day, Hour]
Index: []

In [36]:
null_values = weather_hist.isna().sum()
print("\nNull values:")
null_values



Null values:


Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Summary                     0
Precip Type                 0
Year                        0
Month                       0
Day                         0
Hour                        0
dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
import optuna
from sklearn.model_selection import cross_val_score

# Split the dataset into features (X) and target variable (y)
X = weather_hist.drop(['Summary'], axis=1)
y = weather_hist['Summary']



# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


def objective(trial):
    param = {
        'objective': 'multi:softmax',
        'num_class': 8,
        'eval_metric': 'mlogloss',
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'verbosity': 0
    }

    model = XGBClassifier(**param)
    scores = cross_val_score(model, X, y, cv=5)
    accuracy = scores.mean()
    return accuracy

In [38]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2024-04-04 10:31:15,909] A new study created in memory with name: no-name-d1a3e25d-6388-484d-99ba-1a1876fa4ad9
[I 2024-04-04 10:31:30,088] Trial 0 finished with value: 0.4645776378405252 and parameters: {'eta': 0.29265952978769266, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.963535648076903, 'colsample_bytree': 0.7717330532342757, 'gamma': 0.3456746295462708}. Best is trial 0 with value: 0.4645776378405252.
[I 2024-04-04 10:31:50,350] Trial 1 finished with value: 0.4971075766976716 and parameters: {'eta': 0.21327993010917054, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7894310444528239, 'colsample_bytree': 0.8228247392932925, 'gamma': 0.3814710027648135}. Best is trial 1 with value: 0.4971075766976716.
[I 2024-04-04 10:32:14,227] Trial 2 finished with value: 0.5177046759075463 and parameters: {'eta': 0.07980066246838989, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.9831098775100908, 'colsample_bytree': 0.600926687445652, 'gamma': 0.08439951391009015}. Be

[I 2024-04-04 10:39:56,728] Trial 26 finished with value: 0.6225927164609235 and parameters: {'eta': 0.06705444279666889, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.5980337057876983, 'colsample_bytree': 0.908608810602304, 'gamma': 0.4123935905475438}. Best is trial 13 with value: 0.7643715129128077.
[I 2024-04-04 10:40:18,085] Trial 27 finished with value: 0.5331411101451339 and parameters: {'eta': 0.09511864878716986, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.5405434275072819, 'colsample_bytree': 0.9558182919612795, 'gamma': 0.27153964658662216}. Best is trial 13 with value: 0.7643715129128077.
[I 2024-04-04 10:40:36,442] Trial 28 finished with value: 0.6580865468644657 and parameters: {'eta': 0.13142565817975768, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.575298146281915, 'colsample_bytree': 0.8548002998488524, 'gamma': 0.3294672624624889}. Best is trial 13 with value: 0.7643715129128077.
[I 2024-04-04 10:40:56,155] Trial 29 finished with value: 0.6

[I 2024-04-04 10:48:20,543] Trial 53 finished with value: 0.75817632705132 and parameters: {'eta': 0.03859735630730796, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5270331783518846, 'colsample_bytree': 0.9748668480712602, 'gamma': 0.25631666160440836}. Best is trial 31 with value: 0.7649868284539593.
[I 2024-04-04 10:48:38,765] Trial 54 finished with value: 0.6843235476965143 and parameters: {'eta': 0.0229572660421692, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.5602189320155861, 'colsample_bytree': 0.9480145670068574, 'gamma': 0.318906555518477}. Best is trial 31 with value: 0.7649868284539593.
[I 2024-04-04 10:48:56,338] Trial 55 finished with value: 0.6759906603326814 and parameters: {'eta': 0.05026561361616491, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5853332671047891, 'colsample_bytree': 0.9288459569832397, 'gamma': 0.20038563806854784}. Best is trial 31 with value: 0.7649868284539593.
[I 2024-04-04 10:49:13,774] Trial 56 finished with value: 0.6

[I 2024-04-04 10:56:26,610] Trial 80 finished with value: 0.6754393125900083 and parameters: {'eta': 0.09471729370938337, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5612227789697702, 'colsample_bytree': 0.6650285160426769, 'gamma': 0.25419355173683494}. Best is trial 78 with value: 0.7651328584476055.
[I 2024-04-04 10:56:44,275] Trial 81 finished with value: 0.7630783003445344 and parameters: {'eta': 0.01959808630482995, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5295210745042671, 'colsample_bytree': 0.6352272748862521, 'gamma': 0.27538223413531726}. Best is trial 78 with value: 0.7651328584476055.
[I 2024-04-04 10:57:01,934] Trial 82 finished with value: 0.7609609758413101 and parameters: {'eta': 0.03717923192170516, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5104711300298228, 'colsample_bytree': 0.7329522960044697, 'gamma': 0.359365794184496}. Best is trial 78 with value: 0.7651328584476055.
[I 2024-04-04 10:57:19,313] Trial 83 finished with value:

In [39]:
from sklearn.metrics import classification_report, confusion_matrix

# Use the best hyperparameters found by Optuna
best_params = study.best_params
model = XGBClassifier(**best_params)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Generate confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Generate classification reports
train_classification_report = classification_report(y_train, y_train_pred)
test_classification_report = classification_report(y_test, y_test_pred)

# Print the results
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

print("\nTrain Confusion Matrix:")
print(train_conf_matrix)

print("\nTest Confusion Matrix:")
print(test_conf_matrix)

print("\nTrain Classification Report:")
print(train_classification_report)

print("\nTest Classification Report:")
print(test_classification_report)


Train Accuracy: 0.8828905170390843
Test Accuracy: 0.8851228033581895

Train Confusion Matrix:
[[60617    51   126     0     0     0     0     3]
 [   72  5648     0     1     0     0     0     0]
 [    1     0  1158     2     0    12     0     0]
 [ 8339    25     2   262     0     0     0     0]
 [   61     0     0     0     0     0     0     0]
 [    0     1    90     0     0    33     0     0]
 [  116     0     0     0     0     0     0     0]
 [   70    11     0     0     0     0     0     5]]

Test Confusion Matrix:
[[15195    11    31     0     0     0     0     1]
 [   16  1418     0     0     0     0     0     0]
 [    1     0   306     1     0     2     1     0]
 [ 2057    10     1    48     0     0     0     0]
 [    3     0     0     0     0     0     0     0]
 [    0     0    26     0     0     5     0     0]
 [   18     0     0     0     0     0     0     0]
 [   18     6     0     0     0     0     0     2]]

Train Classification Report:
              precision    recall 

C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\skle

In [40]:
import pickle
filename = 'savemodel.sav'
pickle.dump(model, open(filename, 'wb'))

In [41]:
load_model = pickle.load(open(filename, 'rb'))

In [42]:
X_test.head()

Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
41923         9.777778                  8.222222      0.96            10.9480   
6284         16.161111                 16.161111      0.78             0.7245   
36170        14.283333                 14.283333      0.96             0.0000   
33623        11.666667                 11.666667      0.86             0.0000   
85765         2.083333                  2.083333      0.92             0.0000   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
41923                     173           6.0697           0   
6284                      308           9.9820           0   
36170                       0          15.8263           0   
33623                       0          16.1000           0   
85765                       0           1.5134           0   

       Pressure (millibars)  Precip Type  Year  Month  Day  Hour  
41923               1019.53            0  2010     11   19    20  
6284                1019.31            0  2006      5   26    19  
36170               1016.77            0  2010      8   23     1  
33623               1017.60            0  2009      9   30    23  
85765               1033.93            0  2015     11    2    19

In [43]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19177 entries, 41923 to 82176
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Temperature (C)           19177 non-null  float64
 1   Apparent Temperature (C)  19177 non-null  float64
 2   Humidity                  19177 non-null  float64
 3   Wind Speed (km/h)         19177 non-null  float64
 4   Wind Bearing (degrees)    19177 non-null  int64  
 5   Visibility (km)           19177 non-null  float64
 6   Loud Cover                19177 non-null  int64  
 7   Pressure (millibars)      19177 non-null  float64
 8   Precip Type               19177 non-null  int64  
 9   Year                      19177 non-null  int64  
 10  Month                     19177 non-null  int64  
 11  Day                       19177 non-null  int64  
 12  Hour                      19177 non-null  int64  
dtypes: float64(6), int64(7)
memory usage: 2.0 MB


In [44]:
weather_hist.head()

Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   Summary  Precip Type  Year  Month  Day  Hour  
0        0            0  2006      3   31    22  
1        0            0  2006      3   31    23  
2        0            0  2006      4    1     0  
3        0            0  2006      4    1     1  
4        0            0  2006      4    1     2

In [45]:
input_data = [[9.5, 7.4, 0.8, 10.2, 200, 
               16.0, 0, 1016.0, 0, 2024, 4, 1, 3]]  # Example input data

# Make predictions
predictions = model.predict(input_data)


In [46]:

# Output the predictions
print("Predicted Summary:", predictions)

Predicted Summary: [0]
